{% set version = "3.0.0" %}

package:
    name: anacore-utils
    version: {{ version }}

source:
  path: ..
  #git_url: https://github.com/bialimed/anacore-utils
  #git_rev: {{ version }}

build:
  number: 0

requirements:
    build:
        - python 3.6
        - setuptools
        - pip
    run:
        - python 3.6

about:
    summary: Scripts for easily process NGS data from medical centers. This package contains several aggregators, converters, filters, wrappers, etc.
    license: GNU GPL v3
    home: https://github.com/bialimed/anacore-utils
    doc_source_url: https://github.com/bialimed/anacore-utils/blob/{{ version }}/README.md
