{% set version = "2.5.0" %}

package:
    name: anacore-utils
    version: {{ version }}

source:
    path: ..

requirements:
    build:
        - python 3.6.7
        - setuptools
    run:
        - python 3.6.7

about:
    summary: "Contains scripts, rules/components and resources for workflow managers and web components and JS libraries developped for NGS in IUCT Oncopole."
    license: "GNU GPL v3"
    home: https://github.com/bialimed/AnaCore-utils
